FROM zeromq/zeromq

MAINTAINER Phaninder <pasupulaphani@gmail.com>

ENV BASE_DIR          /usr/test

RUN mkdir -p $BASE_DIR
VOLUME $BASE_DIR

WORKDIR $BASE_DIR
ADD . $BASE_DIR

RUN apt-get install -y python-setuptools

##################################################
######### setup zeromq/node_client  #########
# nodejs
RUN apt-get update && apt-get -qq update && apt-get install -y --force-yes \
  curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs
WORKDIR $BASE_DIR/zeromq/node_client
RUN if [ -d node_modules ]; then rm -r node_modules; fi
RUN npm install
#########


WORKDIR $BASE_DIR
