FROM zeromq/zeromq

MAINTAINER Phaninder <pasupulaphani@gmail.com>

ENV BASE_DIR          /usr/test

RUN mkdir -p $BASE_DIR

WORKDIR $BASE_DIR
ADD . $BASE_DIR

####################################################
######### setup test/zeromq/python_client  #########
# Install pyzmq: Python bindings for ZeroMQ
RUN apt-get update && apt-get -qq update && apt-get install -y python3 python3-dev python3-pip
RUN pip3 install -r $BASE_DIR/zeromq/python_client/requirements.txt
#########
