FROM zeromq/zeromq

MAINTAINER Phaninder <pasupulaphani@gmail.com>

ENV BASE_DIR          /usr/test

RUN mkdir -p $BASE_DIR

WORKDIR $BASE_DIR
ADD . $BASE_DIR

RUN apt-get install -y python-setuptools

##################################################
######### setup zeromq/node_client  #########
RUN apt-get update && apt-get -qq update && apt-get install -y --force-yes \
  curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs
COPY zeromq/node_client/package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mv /tmp/node_modules  /usr/test/zeromq/node_client/
#########
