FROM zeromq/zeromq

MAINTAINER Phaninder <pasupulaphani@gmail.com>

ENV BASE_DIR          /usr/test

RUN mkdir -p $BASE_DIR
VOLUME $BASE_DIR

WORKDIR $BASE_DIR
ADD . $BASE_DIR

# Install pyzmq: Python bindings for ZeroMQ
RUN easy_install3 pip
RUN pip3 install -r $BASE_DIR/zeromq/requirements.txt

CMD ["python3", "test/zeromq/suite.py"]
ENTRYPOINT ["python3", "test/zeromq/suite.py"]
