version: '2'
services:
  zeromq:
    build:
      dockerfile: Dockerfile.zeromq
      context: ./
    environment:
      HOST: zeromq
      PORT: 4242
      LANG: en
    command: 'python3 zeromq/server.py'
    working_dir: /usr/zerorpc
    expose:
      - 4242
    volumes:
      - .:/usr/zerorpc
    stdin_open: true
    tty: true
    restart: always
  zeromq-test-sut:
    build:
      dockerfile: Dockerfile.test
      context: ./
    environment:
      ZEROMQ_HOST: zeromq
      ZEROMQ_PORT: 4242
      LANG: en
    command: ["./wait-for-it.sh", "-t", "300", "127.0.0.1:4242", "--strict", "--", "python3", "test/zeromq/suite.py"]
    working_dir: /usr/test
    depends_on:
      - zeromq
    links:
      - zeromq
    volumes:
      - .:/usr/test
    stdin_open: true
    tty: true
    restart: always
